spring.application.name=banco-dwf

# ===============================
# DATASOURCE (SQL Server - Azure)
# ===============================
spring.datasource.url=jdbc:sqlserver://sql-dws-05a2919c.database.windows.net:1433;databaseName=BancoDWF;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=adminuser
spring.datasource.password=rB1Q4Mnbrmj4zRpIsvcFJRMxV6G
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
